### ISSUE TITLE
Chalkboard support?

### ISSUE THREAD

**Issue by lenalebt** [SteffenPL/MyPaintEdSlides#3]
Hi!

I have not yet tried out the project, but checked out your example presentations. If you added support for "chalkboard" in reveal, you could additionally add simple notes while doing the presentation: https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard - what do you think? See here for a demo: https://rajgoel.github.io/reveal.js-demos/chalkboard-demo.html

I'll most probably check out the project later today, looks very promising :-).

**Comment by SteffenPL** [comment]
Hi,
the project is so far in an experimental state; it just fits my needs and I didn't bother making it user-friendly, yet.
Since there is now one potential user, I could spend some time this week to make it work properly.

I will try to update the readme and provide better examples today. 

I actually used chalkboard in a recent talk and it was very useful.
Somehow the current version online is broken, I will fix that.

**Comment by SteffenPL** [comment]
Here is the link to the recent talk with Chalkboard support:
https://steffenpl.github.io/MyPaintEdSlides/test/position_based_methods/index.html#/

(The hotkeys are 'C' and 'B')

**Comment by SteffenPL** [comment]
Right now, it would already work in two ways: Either by manually adjusting
https://github.com/SteffenPL/MyPaintEdSlides/tree/master/html_templates
or by manually changing the generated HTML files.

Chalkboard support per default is a good idea. I will add it today.

**Comment by lenalebt** [comment]
Wow, nice :). No need to hurry, though.

 As I said, I wanted to try the project in detail later on today. I'll check if I can get it to work with the templates already :). I know some python as well, so in case the docs are not perfect, it's not too bad. I can work it out (at least I hope so :-))

**Comment by SteffenPL** [comment]
Hi, 

I moved all my presentations into a separate repository and added a basic example
(with chalkboard support). Check also the updated readme!

https://steffenpl.github.io/MyPaintEdSlides/examples/mypaint/build/index.html#/

Please let me know if something does not work or features could be added.

**Comment by lenalebt** [comment]
Okay, I got it working! There are a few things that I did not understand at first, for example that the filename wildcards are expected to be passed to the application. My bash already expands them. I'll try to make a pull request to allow for both, and for stuff (iff any) that could be added to the readme. Unsure if I'll get that done today.

The chalkboard support though: I confirm it working, really like it! You can close this ticket, I'll open additional ones if needed.

**Comment by SteffenPL** [comment]
Great! Yes, the wildcards thing is limiting...

I guess it should use the `nargs` 
https://docs.python.org/3/library/argparse.html#nargs 
Maybe like,
`parser.add_argument("input", nargs="+", help="All input .ora files", type=str)`

Just tell me if I should implement it. Of course, PRs are welcome 😃

**Comment by lenalebt** [comment]
Nothing to do for you anymore, did not know where to leave feedback so I'm doing it here:

I did a talk using this tool today, and I really liked it. Creating the slides worked like a charm. I am considering making it a bit easier to use (install it to the system, anything like that), might add a PR for that some time.

Besides that, just wanted to say "thank you", since it really helped me already and I do absolutely appreciate you putting this on github :-).
